language: php

sudo: false

cache:
    directories:
        - bin
        - vendor

php:
    - 7.1
    - 7.0
    - 5.6
    - hhvm

services:
  - mongodb

matrix:
    fast_finish: true
    allow_failures:
        - php: hhvm

before_install:
    - phpenv config-rm xdebug.ini || true

install:
    - composer update --prefer-dist --ignore-platform-reqs

before_script:
    - test/app/console doctrine:database:create -vvv
    - test/app/console doctrine:schema:create -vvv

script:
    - composer validate --strict

    - bin/phpunit
