name: Build

on:
  push: ~
  pull_request: ~
  release:
    types: [created]
  schedule:
    -
      cron: "0 1 * * 6" # Run at 1am every Saturday

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php: [7.3, 7.4, 8.0]
        symfony: [4.4.*, 5.2.*]
        phpunit: [^8.0, ^9.0]
        php-matcher: [^5.0, ^6.0]

    steps:
    - uses: actions/checkout@v2

    - name: "Setup PHP"
      uses: "shivammathur/setup-php@v2"
      with:
        php-version: "${{ matrix.php }}"
        coverage: "none"

    - name: "Restrict Symfony version"
      run: |
        composer global require --no-progress --no-scripts --no-plugins "symfony/flex:^1.10"
        composer config extra.symfony.require "${{ matrix.symfony }}"

    - name: "Restrict coduo/php-matcher version"
      run: "composer require \"coduo/php-matcher:${{ matrix.php-matcher }}\" --no-update --no-scripts"

    - name: "Restrict phpunit/phpunit version"
      run: "composer require \"phpunit/phpunit:${{ matrix.phpunit }}\" --no-update --no-scripts"

    - name: "Validate composer.json and composer.lock"
      run: "composer validate --strict"

    - name: "Cache Composer packages"
      id: "composer-cache"
      uses: "actions/cache@v2"
      with:
        path: "vendor"
        key: "${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}"
        restore-keys: |
          ${{ runner.os }}-php-

    - name: "Install dependencies"
      if: "steps.composer-cache.outputs.cache-hit != 'true'"
      run: "composer install --prefer-dist --no-progress --no-suggest"

    - name: "Run analyse"
      run: composer analyse

    - name: "Run tests"
      run: vendor/bin/phpunit
